### ISSUE TITLE
GitHubAPI - Suggestion - git like syntax

### ISSUE THREAD

**Issue by nicholasosaka** [mibac138/CC#3]
Maybe adding something like git? Adding a mini-version-control would be nice.
A few commands:
git clone <url> <destination>
git commit <message>
git push <destination (in the computer)>
etc.

You are doing great work! :+1: Keep it up!

**Comment by mibac138** [comment]
Nice idea, i will work on it! Thanks! :)
BTW. sorry for so late response, but i wasn't able do respond faster :C
